web/documentserver-example/ruby/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match '/index',    to: 'home#index',    via: 'get'
  match '/editor',    to: 'home#editor',    via: 'get'
  match '/sample',    to: 'home#sample',    via: 'get'
  match '/remove',    to: 'home#remove',    via: 'get'

  match '/upload',    to: 'home#upload',    via: 'post'
  match '/convert',    to: 'home#convert',    via: 'get'
  match '/track',    to: 'home#track',    via: 'post'

end

web/documentserver-example/ruby/app/controllers/home_controller.rb
require 'net/http'

class HomeController < ApplicationController
  def index
  end

  def editor

    DocumentHelper.init(request.remote_ip, request.base_url)

    @file = FileModel.new(:file_name => params[:fileName], :mode => params[:editorsMode], :type => params[:editorsType], :user_ip => request.remote_ip, :lang => cookies[:ulang], :uid => cookies[:uid], :uname => cookies[:uname])

  end

  def sample

    DocumentHelper.init(request.remote_ip, request.base_url)

    file_name = DocumentHelper.create_demo(params[:fileExt], params[:sample], cookies[:uid], cookies[:uname])
    redirect_to :controller => 'home', :action => 'editor', :fileName => file_name

  end

  def upload

    DocumentHelper.init(request.remote_ip, request.base_url)

    begin
      http_posted_file = params[:file]
      file_name = http_posted_file.original_filename
      cur_size = http_posted_file.size

      if DocumentHelper.file_size_max < cur_size || cur_size <= 0
        raise 'File size is incorrect'
      end

      cur_ext = File.extname(file_name).downcase

      unless DocumentHelper.file_exts.include? cur_ext
        raise 'File type is not supported'
      end

      file_name = DocumentHelper.get_correct_name(file_name)

      File.open(DocumentHelper.storage_path(file_name, nil), 'wb') do |file|
        file.write(http_posted_file.read)
      end

      DocumentHelper.create_meta(file_name, cookies[:uid], cookies[:uname])

      render :text =>  '{ "filename": "' + file_name + '"}'
    rescue => ex
      render :text =>  '{ "error": "' + ex.message + '"}'
    end

  end

  def convert

    begin
      file_name = params[:filename]
      file_uri = DocumentHelper.get_file_uri(file_name)
      extension = File.extname(file_name)
      internal_extension = DocumentHelper.get_internal_extension(FileUtility.get_file_type(file_name))

      if DocumentHelper.convert_exts.include? (extension)
        key = ServiceConverter.generate_revision_id(file_uri)
        percent, new_file_uri  = ServiceConverter.get_converted_uri(file_uri, extension.delete('.'), internal_extension.delete('.'), key, true)

        if percent != 100
          render :text => '{ "step" : "' + percent.to_s + '", "filename" : "' + file_name + '"}'
          return
        end

        correct_name = DocumentHelper.get_correct_name(File.basename(file_name, extension) + internal_extension)

        uri = URI.parse(new_file_uri)
        http = Net::HTTP.new(uri.host, uri.port)

        if new_file_uri.start_with?('https')
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        end

        req = Net::HTTP::Get.new(uri.request_uri)
        res = http.request(req)
        data = res.body

        if data == nil
          raise 'stream is null'
        end

        File.open(DocumentHelper.storage_path(correct_name, nil), 'wb') do |file|
          file.write(data)
        end

        file_name = correct_name

        DocumentHelper.create_meta(file_name, cookies[:uid], cookies[:uname])
      end

      render :text => '{ "filename" : "' + file_name + '"}'
    rescue => ex
      render :text => '{ "error": "' + ex.message + '"}'
    end

  end

  def track

    user_address = params[:userAddress]
    file_name = params[:fileName]

    storage_path = DocumentHelper.storage_path(file_name, user_address)
    body = request.body.read

    if body == nil || body.empty?
      return
    end

    file_data = JSON.parse(body)

    if JwtHelper.is_enabled
      inHeader = false
      token = nil
      if file_data["token"]
        token = JwtHelper.decode(file_data["token"])
      elsif request.headers["Authorization"]
        hdr = request.headers["Authorization"]
        hdr.slice!(0, "Bearer ".length)
        token = JwtHelper.decode(hdr)
        inHeader = true
      else
        raise "Expected JWT"
      end
      if !token
        raise "Invalid JWT signature"
      end

      file_data = JSON.parse(token)
      if inHeader
        file_data = file_data["payload"]
      end
    end

    status = file_data['status'].to_i

    if status == 2 || status == 3 #MustSave, Corrupted

      saved = 0

      begin

        def save_from_uri(path, uristr)
          uri = URI.parse(uristr)
          http = Net::HTTP.new(uri.host, uri.port)

          if uristr.start_with?('https')
            http.use_ssl = true
            http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          end

          req = Net::HTTP::Get.new(uri)
          res = http.request(req)
          data = res.body

          if data == nil
            raise 'stream is null'
          end

          File.open(path, 'wb') do |file|
            file.write(data)
          end
        end

        hist_dir = DocumentHelper.history_dir(storage_path)
        ver_dir = DocumentHelper.version_dir(hist_dir, DocumentHelper.get_file_version(hist_dir) + 1)

        FileUtils.mkdir_p(ver_dir)

        FileUtils.move(storage_path, File.join(ver_dir, "prev#{File.extname(file_name)}"))
        save_from_uri(storage_path, file_data['url'])

        if (file_data["changesurl"])
          save_from_uri(File.join(ver_dir, "diff.zip"), file_data["changesurl"])
        end

        hist_data = file_data["changeshistory"]
        if (!hist_data)
          hist_data = file_data["history"].to_json
        end
        if (hist_data)
          File.open(File.join(ver_dir, "changes.json"), 'wb') do |file|
            file.write(hist_data)
          end
        end

        File.open(File.join(ver_dir, "key.txt"), 'wb') do |file|
          file.write(file_data["key"])
        end

      rescue StandardError => msg
        saved = 1
      end

      render :text => '{"error":' + saved.to_s + '}'
      return
    end

    render :text => '{"error":0}'
    return

  end

  def remove
    file_name = params[:filename]
    if !file_name
      render :text => '{"success":false}'
      return
    end

    DocumentHelper.init(request.remote_ip, request.base_url)
    storage_path = DocumentHelper.storage_path(file_name, nil)
    hist_dir = DocumentHelper.history_dir(storage_path)

    if File.exist?(storage_path)
      File.delete(storage_path)
    end

    if Dir.exist?(hist_dir)
      FileUtils.remove_entry_secure(hist_dir)
    end

    render :text => '{"success":true}'
    return
  end
end

web/documentserver-example/ruby/app/helpers/home_helper.rb
module HomeHelper
end

web/documentserver-example/ruby/app/views/home/editor.html.erb
<%= stylesheet_link_tag "editor" %>

<div class="form">
  <div id="iframeEditor">
  </div>
</div>

<script src="<%= Rails.configuration.urlApi %>"></script>

<script type="text/javascript" language="javascript">

    var docEditor;

    var innerAlert = function (message) {
        if (console && console.log)
            console.log(message);
    };

    var onAppReady = function () {
        innerAlert("Document editor ready");
    };

    var onDocumentStateChange = function (event) {
        var title = document.title.replace(/\*$/g, "");
        document.title = title + (event.data ? "*" : "");
    };

    var onRequestEditRights = function () {
        location.href = location.href.replace(RegExp("action=view?&", "i"), "");
    };

    var onError = function (event) {
        if (event)
            innerAlert(event.data);
    };

    var onOutdatedVersion = function (event) {
        location.reload(true);
    };

    var сonnectEditor = function () {

        var config = <%= raw @file.get_config.to_json %>;

        config.width = "100%";
        config.height = "100%";
        config.events = {
            'onAppReady': onAppReady,
            'onDocumentStateChange': onDocumentStateChange,
            'onError': onError,
            'onOutdatedVersion': onOutdatedVersion
        };

        <%
            h = @file.get_history
            if h %>
            config.events['onRequestHistory'] = function () {
                docEditor.refreshHistory(<%= raw h[:hist].to_json %>);
            };
            config.events['onRequestHistoryData'] = function (event) {
                var ver = event.data;
                var histData = <%= raw h[:histData].to_json %>;
                docEditor.setHistoryData(histData[ver]);
            };
            config.events['onRequestHistoryClose'] = function () {
                document.location.reload();
            };
            <% end
        %>

        docEditor = new DocsAPI.DocEditor("iframeEditor", config);
    };

    if (window.addEventListener) {
        window.addEventListener("load", сonnectEditor);
    } else if (window.attachEvent) {
        window.attachEvent("load", сonnectEditor);
    }

</script>

web/documentserver-example/ruby/app/views/home/index.html.erb
<div class="top-panel"></div>
<div class="main-panel">
  <span class="portal-name">ONLYOFFICE Document Editors</span>
  <br />
  <br />
  <span class="portal-descr">Get started with a demo-sample of ONLYOFFICE Document Editors, the first html5-based editors. You may upload your own documents for testing using the "Upload file" button and selecting the necessary files on your PC.</span>

  <table class="user-block-table" cellspacing="0" cellpadding="0">
    <tbody>
      <tr>
        <td width="30%" valign="middle">
          <span class="select-user">Username:</span>
          <select class="select-user" id="user">
            <option value="uid-1">Jonn Smith</option>
            <option value="uid-2">Mark Pottato</option>
            <option value="uid-3">Hamish Mitchell</option>
          </select>
        </td>
        <td width="70%" valign="middle">Select user name before opening the document; you can open the same document using different users in different Web browser sessions, so you can check out multi-user editing functions.</td>
        </tr>
        <tr>
          <td width="30%" valign="middle">
            <select class="select-user" id="language">
              <option value="en">English</option>
              <option value="bg">Bulgarian</option>
              <option value="zh">Chinese</option>
              <option value="cs">Czech</option>
              <option value="nl">Dutch</option>
              <option value="fr">French</option>
              <option value="de">German</option>
              <option value="hu">Hungarian</option>
              <option value="it">Italian</option>
              <option value="ja">Japanese</option>
              <option value="ko">Korean</option>
              <option value="lv">Latvian</option>
              <option value="pl">Polish</option>
              <option value="pt">Portuguese</option>
              <option value="ru">Russian</option>
              <option value="sk">Slovak</option>
              <option value="sl">Slovenian</option>
              <option value="es">Spanish</option>
              <option value="tr">Turkish</option>
              <option value="uk">Ukrainian</option>
              <option value="vi">Vietnamese</option>
            </select>
          </td>
          <td width="70%" valign="middle">Choose the language for ONLYOFFICE editors interface.</td>
        </tr>
    </tbody>
  </table>
  <br />
  <br />

  <div class="help-block">
    <span class="try-descr">Upload your file or create new file</span>
    <br />
    <br />
    <div class="clearFix">
      <div class="upload-panel clearFix">
          <a class="file-upload">
              Upload
              <br />
              File
              <input type="file" id="fileupload" name="file" data-url="<%= upload_path %>" />
          </a>
      </div>
      <div class="create-panel">
          <ul class="try-editor-list clearFix">
              <li><a class="try-editor document" data-type="docx">Create<br />Document</a></li>
              <li><a class="try-editor spreadsheet" data-type="xlsx">Create<br />Spreadsheet</a></li>
              <li><a class="try-editor presentation" data-type="pptx">Create<br />Presentation</a></li>
          </ul>
          <label class="create-sample">
              <input id="createSample" class="checkbox" type="checkbox" />
              Create a file filled with sample content
          </label>
      </div>
    </div>
  </div>

  <%
    DocumentHelper.init(request.remote_ip, request.base_url)
    docs = DocumentHelper.get_stored_files(nil)
    if docs.length > 0 %>

    <div class="help-block">
      <span>Your documents</span>
      <br />
      <br />
      <div class="stored-list">
        <table width="100%" cellspacing="0" cellpadding="0">
          <thead>
            <tr class="tableHeader">
              <td class="tableHeaderCell tableHeaderCellFileName">Filename</td>
              <td colspan="6" class="tableHeaderCell contentCells-shift">Editors</td>
              <td colspan="3" class="tableHeaderCell">Viewers</td>
            </tr>
          </thead>
          <tbody>
            <% docs.each { |d|
              editUrl = "editor?fileName=#{URI::encode(d)}"
              docType = FileUtility.get_file_type(d)
            %>
              <tr class="tableRow" title="<%= d %>">
                <td class="contentCells">
                    <a class="stored-edit <%= docType %>" href="<%= editUrl %>" target="_blank">
                        <span title="<%= d %>"><%= d %></span>
                    </a>
                    <a href="<%= DocumentHelper.get_file_uri(d) %>">
                        <img class="icon-download" src="assets/download-24.png" alt="Download" title="Download" />
                    </a>
                    <a class="delete-file" data-filename="<%= d %>">
                        <img class="icon-delete" src="assets/delete-24.png" alt="Delete" title="Delete" />
                    </a>
                </td>

                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=edit" %>" target="_blank">
                        <img src="assets/desktop-24.png" alt="Open in editor for full size screens" title="Open in editor for full size screens"/>
                    </a>
                </td>
                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=mobile&editorsMode=edit" %>" target="_blank">
                        <img src="assets/mobile-24.png" alt="Open in editor for mobile devices" title="Open in editor for mobile devices"/>
                    </a>
                </td>
                <td class="contentCells contentCells-icon">
                    <% if docType.eql?("text") %>
                        <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=review" %>" target="_blank">
                            <img src="assets/review-24.png" alt="Open in editor for review" title="Open in editor for review"/>
                        </a>
                    <% elsif docType.eql?("spreadsheet") %>
                        <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=filter" %>" target="_blank">
                            <img src="assets/filter-24.png" alt="Open in editor without access to change the filter" title="Open in editor without access to change the filter" />
                        </a>
                    <% end %>
                </td>
                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=comment" %>" target="_blank">
                        <img src="assets/comment-24.png" alt="Open in editor for comment" title="Open in editor for comment"/>
                    </a>
                </td>
                <td class="contentCells contentCells-icon">
                    <% if docType.eql?("text") %>
                        <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=fillForms" %>" target="_blank">
                            <img src="assets/fill-forms-24.png" alt="Open in editor for filling in forms" title="Open in editor for filling in forms"/>
                        </a>
                    <% end %>
                </td>
                <td class="contentCells contentCells-shift contentCells-icon">
                    <% if docType.eql?("text") %>
                        <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=blockcontent" %>" target="_blank">
                            <img src="assets/block-content-24.png" alt="Open in editor without content control modification" title="Open in editor without content control modification"/>
                        </a>
                    <% end %>
                </td>

                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=desktop&editorsMode=view" %>" target="_blank">
                        <img src="assets/desktop-24.png" alt="Open in viewer for full size screens" title="Open in viewer for full size screens"/>
                    </a>
                </td>
                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=mobile&editorsMode=view" %>" target="_blank">
                        <img src="assets/mobile-24.png" alt="Open in viewer for mobile devices" title="Open in viewer for mobile devices"/>
                    </a>
                </td>
                <td class="contentCells contentCells-icon">
                    <a href="<%= "#{editUrl}&editorsType=embedded&editorsMode=embedded" %>" target="_blank">
                        <img src="assets/embeded-24.png" alt="Open in embedded mode" title="Open in embedded mode"/>
                    </a>
                </td>
            </tr>
            <% } %>
          </tbody>
        </table>
      </div>
    </div>

    <% end
  %>

  <br />
  <br />
  <br />
  <div class="help-block">
    <span>Want to learn how it works?</span>
    <br />
    Read the editor <a href="http://api.onlyoffice.com/editors/howitworks">API Documentation</a>
  </div>
  <br />
  <br />
  <br />
  <div class="help-block">
    <span>Any questions?</span>
    <br />
    Please, <a href="mailto:sales@onlyoffice.com">submit your request</a> and we'll help you shortly.
  </div>
</div>

<div id="hint">
  <div class="corner"></div>
  If you check this option the file will be saved both in the original and converted into Office Open XML format for faster viewing and editing. In other case the document will be overwritten by its copy in Office Open XML format.
</div>

<div id="mainProgress">
  <div id="uploadSteps">
    <span id="step1" class="step">1. Loading the file</span>
    <span class="step-descr">The file loading process will take some time depending on the file size, presence or absence of additional elements in it (macros, etc.) and the connection speed.</span>
    <br />
    <span id="step2" class="step">2. File conversion</span>
    <span class="step-descr">The file is being converted into Office Open XML format for the document faster viewing and editing.</span>
    <br />
    <span id="step3" class="step">3. Loading editor scripts</span>
    <span class="step-descr">The scripts for the editor are loaded only once and are will be cached on your computer in future. It might take some time depending on the connection speed.</span>
    <input type="hidden" name="hiddenFileName" id="hiddenFileName" />
    <br />
    <br />
    <span class="progress-descr">Please note, that the speed of all operations greatly depends on the server and the client locations. In case they differ or are located in differernt countries/continents, there might be lack of speed and greater wait time. The best results are achieved when the server and client computers are located in one and the same place (city).</span>
    <br />
    <br />
    <div class="error-message">
      <span></span>
      <br />
      Please select another file and try again. If you have questions please <a href="mailto:sales@onlyoffice.com">contact us.</a>
    </div>
  </div>
  <iframe id="embeddedView" src="" height="345px" width="600px" frameborder="0" scrolling="no" allowtransparency></iframe>
  <br />
  <div id="beginEmbedded" class="button disable">Embedded view</div>
  <div id="beginView" class="button disable">View</div>
  <div id="beginEdit" class="button disable">Edit</div>
  <div id="cancelEdit" class="button gray">Cancel</div>
</div>

<span id="loadScripts" data-docs="<%= Rails.configuration.urlPreloader %>"></span>

<div class="bottom-panel">&copy; Ascensio System SIA <%= Time.now.year %>. All rights reserved.</div>

<%= javascript_include_tag "application" %>

<script language="javascript" type="text/javascript">
    var ConvertExtList = '<%= DocumentHelper.convert_exts.join(",") %>';
    var EditedExtList = '<%= DocumentHelper.edited_exts.join(",") %>';
    var UrlConverter = '<%= convert_path %>';
    var UrlEditor = '<%= editor_path %>';
</script>